# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Copy package and typescript config
COPY package.json tsconfig.json ./

# Install dependencies without running prepare/build
RUN npm install --ignore-scripts

# Copy source files
COPY src ./src

# Build and prune dev dependencies
RUN npm run build && npm prune --production

# Default command to start the MCP server
CMD ["node", "dist/index.js"]
